backend:
  name: git-gateway
  branch: main  # Asegúrate de usar la rama principal de tu repositorio

media_folder: "static/uploads"  # Carpeta para subir imágenes
public_folder: "/uploads"       # Ruta pública para imágenes

collections:
  - name: "images"
    label: "Images"
    folder: "static/uploads"
    create: true
    fields:
      - { label: "File", name: "file", widget: "image" }
      - { label: "Description", name: "description", widget: "string" }

  - name: "pages"
    label: "Pages"
    folder: "admin"
    create: false  # Evita crear nuevas páginas desde el CMS
    extension: "html"
    format: "html"
    fields:
      - { label: "Content", name: "body", widget: "markdown" }
