backend:
  name: git-gateway
  branch: main # La rama de GitHub que usas

media_folder: "static/uploads" # Carpeta para subir imágenes
public_folder: "/uploads" # Ruta pública para imágenes

collections:
  - name: "images"
    label: "Images"
    folder: "static/uploads"
    create: true
    fields:
      - { label: "File", name: "file", widget: "image" }
      - { label: "Description", name: "description", widget: "string" }
