backend:
  name: git-gateway
  branch: main

media_folder: "static/uploads"
public_folder: "/uploads"

collections:
  - name: "images"
    label: "Images"
    folder: "static/uploads"
    create: true
    fields:
      - { label: "File", name: "file", widget: "image" }
      - { label: "Description", name: "description", widget: "string" }

  - name: "gallery"
    label: "Gallery JSON"
    folder: "static/uploads"
    extension: "json"
    create: true
    fields:
      - { label: "Images", name: "images", widget: "list", field: { label: "File", name: "file", widget: "image" } }
