backend:
  name: git-gateway
  branch: main

media_folder: "static/uploads"
public_folder: "static/uploads"

collections:
  - name: "gallery"
    label: "Gallery JSON"
    folder: "static/uploads"
    create: true
    extension: "json"
    slug: "uploads"
    fields:
      - label: "Images"
        name: "images"
        widget: "list"
        field:
          label: "File"
          name: "file"
          widget: "image"
